#!/bin/sh
# /etc/uci-defaults/99-cellular-setup
# Automated first-boot setup for Mesh MK01K21 cellular modem & MBIM

# The DTS gpio-export node owns GPIO 6 and boots the active-low modem power
# line asserted. Enable the service only for deliberate later power cycles.
[ -x /etc/init.d/modem-power ] && /etc/init.d/modem-power enable

# Setup MBIM network interface if not present
if ! uci -q get network.wan_cellular >/dev/null; then
	uci set network.wan_cellular=interface
	uci set network.wan_cellular.proto='mbim'
	uci set network.wan_cellular.device='/dev/cdc-wdm0'
	uci set network.wan_cellular.apn='internet'
	uci set network.wan_cellular.pdptype='ip'
	uci set network.wan_cellular.metric='10'
	uci set network.wan_cellular.auto='1'
	uci set network.wan_cellular.peerdns='1'
	uci set network.wan_cellular.defaultroute='1'
	uci commit network
fi

# Add wan_cellular to the wan firewall zone
if uci -q get firewall.@zone[1] >/dev/null; then
	uci add_list firewall.@zone[1].network='wan_cellular'
	uci commit firewall
fi

exit 0
